#include<stdio.h>
#include<stdlib.h> 
#include<string.h>
#include<sys/types.h>
#include<unistd.h>
/* ex2
during this program execution amount of free memory decreasing
but si amd so do not cange 
since there is anough physical memory to execute this proces 
without involving hard disk
*/
/* ex3
in "top" I can see amount of virtual and actual memory that is used by a proces
also actual memory allocated to this proces is bigger than memory we allocate for
data (since code size and outher staff generated by compiler also requaer some memory)
*/

int main(void){
	int** arr = malloc(sizeof(int*)*10);
   	for(int i = 0; i < 10; i++){
   		arr[i] = malloc(1024*1024*10);
   		memset(arr[i], 0, 1024*1024*10);
   		sleep(1);
   	}
   	for(int i = 0; i < 10; i++){
   		free(arr[i]);
   	}

   	free(arr);
    return 0; 
}